#print("my name is nikky")
#print("my surname is vincenzo")
#print(my gender is female)
#print("i am 37 years old")
#print("i am lagos state")


name =input("enter your name:")
print(f"hi {name} nice to meet you")
surname =input("enter your surname: ")
gender =input("sex:")
age = input("how old are you:")
state =input("state of origin:")
occupation = input("what is your occupaion:")
print("my surname is ",surname)
print("my gender is",gender)
print("i am","years old")
print("i am from",state,"state")
print("i am a" ,occupation)
